services:
  - type: web
    name: today-your-day
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DEBUG
        value: "False"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: today-your-day.onrender.com
