services:
  - type: web
    name: today-your-day
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
      python manage.py create_admin
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-production-secret-key
      - key: DEBUG
        value: "False"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: today-your-day.onrender.com
