services:
  - type: web
    name: today-your-day
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input --settings=config.settings.prod
      python manage.py migrate --noinput --settings=config.settings.prod
      python manage.py create_admin
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
