# Generated by Django 5.1.7 on 2025-03-31 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RollingPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rollingpaper_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollingpapers', to='recipients.recipient')),
            ],
        ),
    ]
