# Generated by Django 5.1.7 on 2025-03-31 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_remove_recipient_created_at_alter_recipient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
